### ISSUE TITLE
Support for use in offline bundle?

### ISSUE THREAD

**Issue by jasoncleo** [jribeiro/babel-plugin-jsx-property-alias#7]
Hi,

The instructions don't seem to define whether this plugin can be used within offline bundles?

using `react-native start --projectRoots $PWD/appium,$PWD` all works fine for the Metro bunder, but we also want to generate a APK that can be used for our CI deployments of APKs for automation Appium tests, however the `react-native bundle` command doesn't recognise the --projectRoots option, so I am not sure how I can go about creating a bundle for that purpose.

It's probably a sign that I don't quite understand how the babel plugin works, but I assumed that it was pushing test IDs into accessibility tags in static JS before executing the Metro bundler, but is it doing the subsititution on the fly? (hence making it unusable for offline bundles?)

Regards,
Jason

**Comment by jribeiro** [comment]
Hey Jason,

Thanks for reporting that. I've released version 2 of this plugin which should make this much easier. 

From the README:
To address this issue this plugin, **from version 2**, allows you to whitelist a set of environments through the `includeInEnvironments` option. When this option is set, the plugin will only run when the value of `ALIAS_ENVIRONMENT` is whitelisted.

```json
{
  "presets": [
    "react-native"
  ],
  "plugins": [
    ["jsx-property-alias", {
      "includeInEnvironments": ["QA"],
      "properties": {
        "testID": "accessibilityLabel"
      }
    }]
  ]
}
```

You can now run the app like:

```bash
ALIAS_ENVIRONMENT=QA react-native start [--reset-cache]
```

Or if you want to bundle the JS:

```bash
ALIAS_ENVIRONMENT=QA react-native bundle [--reset-cache] # other options...
```

Hope it helps. but feel free to re-open if it doesn't.
